# Generated by Django 3.1.3 on 2020-11-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
