# Generated by Django 3.1.3 on 2020-11-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_collection', '0002_auto_20201111_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
