# Generated by Django 3.1.3 on 2020-11-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_collection', '0003_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
